nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /home/ubuntu/server/certs:/etc/nginx/certs:ro
    - /home/ubuntu/server/vhostd:/etc/nginx/vhost.d
    - /home/ubuntu/server/html:/usr/share/nginx/html
  labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  
letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: always
  environment:
    - NGINX_PROXY_CONTAINER=nginx-proxy
  volumes:
    - /home/ubuntu/server/certs:/etc/nginx/certs:rw
    - /home/ubuntu/server/vhostd:/etc/nginx/vhost.d
    - /home/ubuntu/server/html:/usr/share/nginx/html
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy:rw

www:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /home/ubuntu/server/www:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=hola.jegod.com,www.hola.jegod.com

wordpress:
  image: wordpress:php7.4-apache
  restart: always
  expose:
    - "80"
  volumes:
    - /home/ubuntu/server/wordpress:/var/www/html
  environment:
    WORDPRESS_DB_HOST: mysql:3306
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: CuentaDeJeGodEnNameCheap#2020!
    WORDPRESS_DB_NAME: wordpress
    VIRTUAL_HOST: jegod.com,www.jegod.com
    LETSENCRYPT_HOST: jegod.com,www.jegod.com
    LETSENCRYPT_EMAIL: jegodsas@gmail.com
  links:
    - mysql:mysql

mysql:
  image: mariadb:10.5.5-focal
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_ROOT_PASSWORD: CuentaDeJeGodEnNameCheap#2020!
    MYSQL_USER: Checho
    MYSQL_PASSWORD: ChechoMexico#2018!
  volumes:
    - /home/ubuntu/server/wordpress/database:/var/lib/mysql

correos:
  image: analogic/poste.io
  restart: always
  expose:
    - "25"
    - "80"
    - "443"
    - "110"
    - "143"
    - "465"
    - "587"
    - "993"
    - "995"
  volumes:
    - /home/ubuntu/server/correos:/data
  environment:
    - HTTPS=ON
    - VIRTUAL_HOST=sarasa.com,www.sarasa.com,chewin.jegod.com,www.chewin.jegod.com

#rancher:
#  image: rancher/rancher:v2.3.5
#  restart: always
#  expose:
#    - "80"
#  environment:
#    VIRTUAL_HOST: checho.jegod.com,www.checho.jegod.com
#    LETSENCRYPT_HOST: checho.jegod.com
#    LETSENCRYPT_EMAIL: jegodsas@gmail.com
